name: Java Ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

     - name: Build with maven
        uses: mvn -B package --file pom.xml

      - name: Run test
        uses: mvn test



